# imagen base liviana de Python
FROM python:3.12-slim

# directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia del archivo de dependencias
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto donde correrá FastAPI
EXPOSE 8000

# Comando para ejecutar la app usando Uvicorn
#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Comando para iniciar la app en producción
CMD ["gunicorn", "app.main:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]